# Generated by Django 4.2.27 on 2026-01-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_socialmedialink"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["order", "-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="skill",
            options={"ordering": ["order", "name"]},
        ),
        migrations.AddField(
            model_name="project",
            name="featured",
            field=models.BooleanField(
                default=False, help_text="Show in featured section"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="order",
            field=models.PositiveIntegerField(default=0, help_text="Display order"),
        ),
        migrations.AddField(
            model_name="skill",
            name="featured",
            field=models.BooleanField(
                default=False, help_text="Show in featured section"
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="order",
            field=models.PositiveIntegerField(default=0, help_text="Display order"),
        ),
    ]
